# /etc/freeradius/3.0/clients.conf
# Append these blocks. The shared secret must match on each NAS.

client opnsense {
    ipaddr = 192.168.200.128
    secret = testing123
}

client ovs-switch {
    ipaddr = 192.168.200.130
    secret = testing123
}
